export const dom = {
    btnStart: document.querySelector('#btnStart'),
    titleImg: document.querySelector('.title'),
    askPlayers: document.querySelector('.qty-players'),
    overlay: document.querySelector('#overlay2'),
    btn1Player: document.querySelector('#btn1Player'),
    btn2Players: document.querySelector('#btn2Player'),
    btn3Players: document.querySelector('#btn3Player'),
    btnNewGame: document.querySelector('#btnNewGame'),
    btnTake: document.querySelector('#btnTake'),
    btnStop: document.querySelector('#btnStop'),
    playersContainer: document.querySelector('#players-container'),
    divGame: document.querySelector('.result'),
    resultSign: document.createElement('div'),
    lang: document.documentElement,
    btnSpa: document.querySelector('#btnEs'),
    btnEng: document.querySelector('#btnEn'),
    ovelayLang: document.querySelector('#overlay-lang'),
}